name: Workflow 3 - Depth Test

on:
  workflow_call:

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow name
        run: |
          echo "================================"
          echo "This is Workflow 3 - Third level"
          echo "================================"
  
  call-next-workflow:
    uses: ./.github/workflows/workflow4-depth-test.yml
