name: Workflow 4 - Depth Test

on:
  workflow_call:

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow name
        run: |
          echo "================================"
          echo "This is Workflow 4 - Fourth level"
          echo "================================"
  
  call-next-workflow:
    needs: print-name
    uses: ./.github/workflows/workflow5-depth-test.yml
